### ISSUE TITLE
Error running Forge processor task

### ISSUE THREAD

**Issue by ChloeDawn** [hedgehog1029/Launcher#1]
**Creator tools version:** 2.0.2
**JDK version:** 15+36
Attempting to test-launch a Forge 1.16.4 mod pack results in the following exception with their installer
```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: java/sql/Time
	at com.skcraft.launcher.install.ProcessorTask.execute(ProcessorTask.java:93)
	at com.skcraft.launcher.install.Installer$TaskQueue.execute(Installer.java:109)
	at com.skcraft.launcher.install.Installer.executeLate(Installer.java:61)
	at com.skcraft.launcher.update.Updater.update(Updater.java:208)
	at com.skcraft.launcher.update.Updater.call(Updater.java:97)
	at com.skcraft.launcher.update.Updater.call(Updater.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NoClassDefFoundError: java/sql/Time
	at com.google.gson.Gson.<init>(Gson.java:240)
	at com.google.gson.GsonBuilder.create(GsonBuilder.java:569)
	at net.minecraftforge.installertools.ConsoleTool.<clinit>(ConsoleTool.java:31)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:468)
	at com.skcraft.launcher.install.ProcessorTask.execute(ProcessorTask.java:89)
	... 9 more
Caused by: java.lang.ClassNotFoundException: java.sql.Time
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 15 more
```
It seems that SKCraft launcher does not include the SQL module

**Comment by hedgehog1029** [comment]
are you using the `-all` shaded jar?

**Comment by hedgehog1029** [comment]
wait, this is inside a `ProcessorTask`, ignore me.

`at net.minecraftforge.installertools.ConsoleTool.<clinit>(ConsoleTool.java:31)`

seems one of the processors is trying to load that class and failing. i'm not sure *why* that class would be missing though; isn't it in the normal Java distribution? since 1.1, even?

**Comment by hedgehog1029** [comment]
got it figured out, java 9+ doesn't like having no delegated classloader, some platform modules are unavailable for whatever reason.
