### ISSUE TITLE
1.12.2 + forge-1.12.2-14.23.5.2854-installer = 

### ISSUE THREAD

**Issue by sylphio** [hedgehog1029/Launcher#4]
When i try to deploy 1.12.2 client on the last build with forge-1.12.2-14.23.5.2854-installer.

The client fail to launch with the following error.

Exception in thread "main" joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option gameDir, but you asked for only one
	at joptsimple.OptionSet.valueOf(OptionSet.java:179)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:51)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	
If i look into the generated manifest.json. the -gameDir option is set twice.

![image](https://user-images.githubusercontent.com/1335813/102942717-15f9db00-4484-11eb-90fd-6777bf2aef59.png)

**Comment by hedgehog1029** [comment]
looks like i never tested creating a forge 1.12 manifest, whoops!

seems like that 1.12 build uses the modern forge install profile, rather than the legacy one, so there's a bit of a behaviour change. will need to check out some of the other versions too, but this is a pretty simple fix from the looks of things.

**Comment by sylphio** [comment]
Crazy quick😁. Thank, will try tonight.
